### ISSUE TITLE
Trojan?

### ISSUE THREAD

**Issue by Chocorot** [InkboxSoftware/smallEXE#1]
The piano lead to this issue.

![image](https://github.com/InkboxSoftware/smallEXE/assets/79820753/88e3cbbc-a8f5-494b-980f-8d2ab2610caa)

**Comment by Amorousstake5** [comment]
Me also today. I cannot download it through my Edge browser in anyway.

**Comment by Amorousstake5** [comment]
![image](https://github.com/InkboxSoftware/smallEXE/assets/154524818/61d96b83-f081-4e67-88b5-8bd4bbc3fee1)

**Comment by InkboxSoftware** [comment]
Anti-virus software may be triggered by these small EXEs (especially the crinkled version), but that is expected behavior and already explained in the documentation. If you'd prefer to take extra precautions, you can always compile the code on your own machine.
